config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users do
    collection { post :search, to: "users#index"}
    collection { get :search, to: "users#index"}
    get :autocomplete_tag_name, :on => :collection
    member do
      get "profile"
      post "ganti_profile"
    end
  end

  resources :projects do 
    get :dashboard, on: :member
    resources :discussions
    resources :tasks do 
      resources :todos do
        post 'completed'
        resources :discussions
      end
    end
  end

  resources :time_sheets do
    collection do
      delete 'finish' #use delete method to overide link using post data update end time working
      delete 'continue_working' #use delete method to overide link using post to delete the end working time so you can contiue working 
    end
  end
  resources :furloughs
  resources :staff_leaves
  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/notifier/leave_manager_notification.html.erb
<p><%= @greeting %></p>
<p><%= @user.name %> Has proposed leave with detail below :</p>

<p>Proposer : <%= @user.name %> | <%= @user.email %> </p>
<p>Date leave : <%=  @furlough.date %></p>
<p>Reason : <%=  @furlough.reason %></p>

<p><%= link_to "Click here ", edit_furlough_url(@furlough) %>to respond the leave</p>

app/views/notifier/leave_manager_respond.html.erb
<p><%= @greeting %></p>
<p>Your manager <%= @manager.name %> has responded your leave proposal with detail below :</p>

<h2> Detail Proposal </h2>

<p>Proposer : <%= @staff.name %> | <%= @staff.email %> </p>
<p>Leave type : <%= @furlough.leave_type %> </p>
<p>Date leave propose : <%=  @furlough.date %></p>
<p>Reason : <%=  @furlough.reason %></p>

<h2>Leave Propsal Respond</h2>

<p> Leave status : <%= @furlough.approved %></p>
<p> Responded date : <%= @furlough.approved_at %></p>
<p> Detail leave respond reason : <%= @furlough.approved_reason %></p>


<h5> Responded by : <%= @manager.name %> | <%= @manager.email %> </h5>

<p><%= link_to "Click here ", furlough_url(@furlough) %>to see the detail respond</p>

app/views/notifier/leave_seven_day_manager_notification.html.erb
<p><%= @greeting %></p>
<p><%= @user.name %> Has proposed leave with detail below :</p>

<p>Proposer : <%= @user.name %> | <%= @user.email %> </p>
<p>Date leave : <%=  @furlough.date %></p>
<p>Reason : <%=  @furlough.reason %></p>

<p><%= link_to "Click here ", edit_furlough_url(@furlough) %>to respond the leave</p>

app/views/notifier/time_sheet_12am.html.erb
<h1>Late Notification</h1>

<p>
  <%= "#{@greeting}  #{@user.name} " %>
</p>
<p>
  <%= "Please be aware that your starting time agreed with your manager is important and needs to be respected. If you are unable to arrive at 12 AM of your starting time, please text or email your manager to let them know you will be late. It is critical that we are able to manage our client's expectations as to when staff are available. This is for every employee of SoftwareSeni no matter which team you work in. Thanks" if @user.name.present? %>
</p>

app/views/notifier/time_sheet_12am.text.erb
Late Notification

<%= "#{@greeting}  #{@user.name} " %>
<%= "Please be aware that your starting time agreed with your manager is important and needs to be respected. If you are unable to arrive at 12 AM of your starting time, please text or email your manager to let them know you will be late. It is critical that we are able to manage our client's expectations as to when staff are available. This is for every employee of SoftwareSeni no matter which team you work in. Thanks" if @user.name.present? %>

app/views/notifier/time_sheet_forget.html.erb
<h1>Notifier#time_sheet_forget</h1>

<p>
  <%= @greeting %>, find me in app/views/notifier/time_sheet_forget.html.erb
</p>

app/views/notifier/time_sheet_forget.text.erb
Notifier#time_sheet_forget

<%= @greeting %>, find me in app/views/notifier/time_sheet_forget.text.erb

app/views/notifier/time_sheet_submit.html.erb
<h1>SS Hub Notification</h1>

<p>
  <%= "#{@greeting}  #{@user.name} , you started work at #{@time_sheet.date_submitted}" %>
</p>
<p>
  <%= "Start : #{@time_sheet.start_time.strftime('%I:%M %p')}" if @time_sheet.start_time.present? %>
</p>
<p>
  <%= "End: #{@time_sheet.end_time.strftime('%I:%M %p')}" if @time_sheet.end_time.present? %>
</p>

app/views/notifier/time_sheet_submit.text.erb
SS Hub Notification


<%= "#{@greeting}  #{@user.name} , you started work at #{@time_sheet.date_submitted}" %>
<%= "Start : #{@time_sheet.start_time.strftime('%I:%M %p')}" if @time_sheet.start_time.present? %>
<%= "End: #{@time_sheet.end_time.strftime('%I:%M %p')}" if @time_sheet.end_time.present?%>

app/views/notifier/todo_assignation.html.erb
<p>Hi, <b><%= @user_t %></b></p>
 
<p><b><%= @user_s %></b> has assign you "<%= link_to @todo.name, project_task_todo_url(@project, @task, @todo) %>" todo, at "<%= link_to @task.name, project_task_url(@project, @task) %>" task, "<%= link_to @project.name, project_url(@project) %>" project.</p>

<p>Thanks</p>

app/views/notifier/todo_assignation.text.erb
Hi, <%= @user_t %>
 
<%= @user_s %> has assign you "<%= @todo.name %>" todo, at "<%= @task.name %>" task, "<%= @project.name %>" project.

todo url: <%= url_for(project_task_todo_path(@project, @task, @todo)) %>

Thanks

app/views/notifier/todo_completion.html.erb
<p>Hi Everybody,</p>
 
<p><b><%= @user_s %></b> has completed "<%= link_to @todo.name, project_task_todo_url(@project, @task, @todo) %>" todo, at "<%= link_to @task.name, project_task_url(@project, @task) %>" task, "<%= link_to @project.name, project_url(@project) %>" project.</p>

<p>Thanks</p>

app/views/notifier/todo_completion.text.erb
Hi Everybody,
 
<%= @user_s %> has completed "<%= @todo.name %>" todo, at "<%= @task.name %>" task, "<%= @project.name %>" project.

todo url: <%= url_for(project_task_todo_path(@project, @task, @todo)) %>

Thanks