config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users do
    collection { post :search, to: "users#index"}
    collection { get :search, to: "users#index"}
    get :autocomplete_tag_name, :on => :collection
    member do
      get "profile"
      post "ganti_profile"
    end
  end

  resources :projects do 
    get :dashboard, on: :member
    resources :discussions
    resources :tasks do 
      resources :todos do
        post 'completed'
        resources :discussions
      end
    end
  end

  resources :time_sheets do
    collection do
      delete 'finish' #use delete method to overide link using post data update end time working
      delete 'continue_working' #use delete method to overide link using post to delete the end working time so you can contiue working 
    end
  end
  resources :furloughs
  resources :staff_leaves
  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tasks, dependent: :destroy
  has_many :todos

  validates :name, presence: true
  
  has_many :discussions, as: :discussrefer

  def resolved_by_user(user_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :dashboard]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    # @projects_url = Project.all

    @search = Project.search(params[:q])
    @projects = @search.result.page(params[:page]).per(10)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @discussionrefer = @project
    @discussions = @discussionrefer.discussions
    @discussion = Discussion.new

    self.project_stat

    @task = Task.new

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy 
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    @person = @project.users.count
    @persons = @project.users

    self.project_stat

    @discussions_temp = @todo_temp.each do |todo|
      [todo.id]
    end
    @discussion_project =  @project.discussions.where(discussrefer_type: 'Project').count
    @discussion_todos = Discussion.where(discussrefer_type: 'Todo').where(discussrefer_id: @discussions_temp)
    @discussion_last = @discussion_todos.order(created_at: :desc).last(5)
    @discussion_todo =  @discussion_todos.count
    @discussion = @discussion_todo + @discussion_project

    @todos_stat = @project.users
  end

  def project_stat
    @tasks = @project.tasks
    @task_id = @tasks.each do |task|
      [task.id]
    end
    
    @todo_temp = Todo.where(task_id: @task_id).where(project_id: @project.id)
    @todo = @todo_temp.where('completed is null').count
    @todo_completed = @todo_temp.where(completed: 1).count
    @todo_all = @todo_temp.count
    @todo_persen = @todo_completed.to_f / @todo_all.to_f * 100
    @todos = @todo_temp.where('completed is null')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, {:user_ids => []})
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
        <%= simple_form_for @project, html: { class: 'form-horizontal' }, wrapper_mappings: { boolean: :vertical_boolean } do |f| %>
          <%= f.error_notification %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.association :users %>
          <%= f.button :submit %>
        <% end %>

app/views/projects/_form_discussions.html.erb
<%# raise @project.to_yaml %>
<%= simple_form_for([@project, @discussion]) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :content%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/dashboard.html.erb
<!-- BEGIN PAGE CONTAINER-->
 <div class="container-fluid">
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
       <div class="span12">
          <div class="widget">
                <div class="widget-title">
                   <h4><i class="icon-globe"></i>Dashboard: <%= @project.name.capitalize %></h4>
                   <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
                   </span>                    
                </div>
                <div class="widget-body clearfix">
                    <div class="span6">
                      <h4>Progress : <%= @todo_persen > 0 ? @todo_persen.round(1) : 0 %> %</h4>
                      <div class="progress clearfix">
                          <div style="width: <%= @todo_persen %>%;" class="bar"></div>
                      </div>
                      <h4>Task</h4>
                      <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>To Do</th>
                            <th>Completed</th>
                            <th>Total</th>
                            <th>Progress</th>
                            <th>%</th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @todos_stat.each do |stat| %>
                          <% resolved = stat.resolved_todos_by_project(@project.id) %>
                          <% unresolved = stat.unresolved_todos_by_project(@project.id) %>
                          <% total = stat.total_todos_by_project(@project.id) %>
                        <tr>
                            <td><%= stat.name %></td>
                            <td>
                              <span class="label <%= unresolved > resolved ? 'label-important' : 'label-important' %>">
                                <%= unresolved %>
                              </span>
                            </td>
                            <td>
                              <span class="label <%= unresolved < resolved ? 'label-success' : 'label-important' %>">
                                <%= resolved %>
                              </span>
                            </td>
                            <td><%= total %></td>
                            <td>
                              <div class="progress progress-important">
                                <div style="width: <%=  (resolved > 0 && total > 0 ) ? ( resolved.to_f / total.to_f * 100 ).round  : 0 %>%" class="bar"></div>
                              </div>
                            </td>
                            <td><%=  (resolved > 0 && total > 0 ) ? ( resolved.to_f / total.to_f * 100 ).round  : 0 %>%</td>
                            
                        </tr>
                        <% end %>
                        </tbody>
                    </table>
                    <h4>To Do</h4>
                      <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>To Do</th>
                            <th>Create</th>
                            <th>PIC</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @todos.each do |todo| %>
                        <tr>
                            <td><%= link_to todo.name, project_task_path(@project.id, todo.task_id) %></td>
                            <td><%= todo.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
                            <td>
                                <span class=""><%= todo.users.first.name %></span>
                            </td>
                            <td>
                                <span class='<%= todo.completed.present? ? "label label-success" : "label red-color"  %>'>
                                  <%= todo.completed.present? ? "Resolved" : "Not Resolved"  %>
                                </span>
                            </td>
                        </tr>
                        <% end %>
                        </tbody>
                    </table>
                    </div>
                    <div class="span6 circle-state-overview">
                      <h4>Summary</h4>
                      <div class="span3 responsive clearfix" data-tablet="span3" data-desktop="span3">
                          <div class="circle-wrap center">
                              <div class="stats-circle turquoise-color">
                                  <i class="icon-user" ></i>
                              </div>
                              <p class="align:center">
                                  <strong><%= @person %></strong>
                                  Person
                              </p>
                          </div>
                      </div>
                      <div class="span3 responsive clearfix" data-tablet="span3" data-desktop="span3">
                          <div class="circle-wrap">
                              <div class="stats-circle red-color">
                                  <i class="icon-thumbs-down red-color"></i>
                              </div>
                              <p>
                                  <strong><%= @todo %></strong>
                                  To Do
                              </p>
                          </div>
                      </div>
                      <div class="span3 responsive clearfix" data-tablet="span3" data-desktop="span3">
                          <div class="circle-wrap">
                              <div class="stats-circle green-color">
                                  <i class="icon-thumbs-up green-color"></i>
                              </div>
                              <p>
                                  <strong><%= @todo_completed %></strong>
                                  Completed
                              </p>
                          </div>
                      </div>
                      <div class="span12">
                      <h4>Stats</h4>
                      <div data-desktop="span4" data-tablet="span3" class="span3 responsive">
                          <div class="metro-overview turquoise-color clearfix">
                              <div class="display">
                                  <i class="icon-comment-alt"></i>
                                  <div class="percent"><%= @discussion %></div>
                              </div>
                              <div class="details">
                                  <div class="numbers"><%= @discussion %></div>
                                  <div class="title">Comment</div>
                                  <div class="progress">
                                      <div style="width: <%= @discussion %>%" class="bar"></div>
                                  </div>
                              </div>
                          </div>

                      </div>
                      <div data-desktop="span4" data-tablet="span3" class="span3 responsive">
                          <div class="metro-overview red-color clearfix">
                              <div class="display">
                                  <i class="icon-tag"></i>
                                  <div class="percent"><%= @todo_all %></div>
                              </div>
                              <div class="details">
                                  <div class="numbers"><%= @todo_all %></div>
                                  <div class="title">Total To Do</div>
                                  <div class="progress">
                                      <div style="width: <%= @todo_all %>%" class="bar"></div>
                                  </div>
                              </div>
                          </div>

                      </div>
                      <div data-desktop="span4" data-tablet="span3" class="span3 responsive">
                          <div class="metro-overview green-color clearfix">
                              <div class="display">
                                  <i class="icon-calendar"></i>
                                  <div class="percent"><%= @discussion %></div>
                              </div>
                              <div class="details">
                                  <div class="numbers">Project Start</div>
                                  <div class="title"><%= @project.created_at.strftime('%d %B %Y') %></div>
                                  <div class="progress">
                                      <div style="width: 10%" class="bar"></div>
                                  </div>
                              </div>
                          </div>

                      </div>
                      <div data-desktop="span4" data-tablet="span3" class="span3 responsive">
                          <div class="metro-overview blue-color clearfix">
                              <div class="display">
                                  <i class="icon-calendar"></i>
                                  <div class="percent"></div>
                              </div>
                              <div class="details">
                                  <div class="numbers">Time Left</div>
                                  <div class="title"><%= distance_of_time_in_words @project.created_at, Time.now %></div>
                                  <div class="progress">
                                      <div style="width: 10%" class="bar"></div>
                                  </div>
                              </div>
                          </div>
                        </div>
                        <div class="span10">
                          <h4>Last Comment</h4>
                          <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Discussion</th>
                            </tr>
                            </thead>
                            <tbody>
                            <% @discussion_last.each do |discussion| %>
                            <tr>
                                <td>
                                  <%= link_to discussion.content.truncate(10),project_task_todo_path(@project.id, Todo.find(discussion.discussrefer_id).task_id, discussion.discussrefer_id) %> <br/>by 
                                  <%= discussion.user.name %> <br/> at 
                                  <%= discussion.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
                            </tr>
                            <% end %>
                            </tbody>
                        </table>
                        </div>
                      </div>
                </div>
          </div>
       </div>
    </div>
    <!-- END PAGE CONTENT-->         
 </div>
 <!-- END PAGE CONTAINER-->

app/views/projects/edit.html.erb
<div class="row-fluid">
 <div class="span12">
    <div class="widget">
      <div class="widget-title">
         <h4><i class="icon-book"></i>Editing Project</h4>
      </div>
      <div class="widget-body">

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<!-- BEGIN GALLERY MANAGER PORTLET-->
              <div class="widget">
                <div class="widget-title">
                  <h4><i class="icon-camera-retro"></i>Projects</h4>
                  <span class="tools">
                  <a href="javascript:;" class="icon-chevron-down"></a>
                </div>
                <div class="widget-body">
                  <!-- BEGIN GALLERY MANAGER PANEL-->
                  <div class="row-fluid">
                    <div class="span4">
                      <%= link_to  new_project_path, class: "btn btn-primary"  do %>
                            <i class="icon-plus icon-white"></i> Project
                        <% end %>
                    </div>
                    <div class="span8">
                      <div class="pull-right">
                        <%= search_form_for @search, url: projects_path do |g| %>
                          <%= g.text_field :name_cont, placeholder: "Search Project" %>
                          <%= g.submit  class: "btn btn-primary" do %>
                          <i class="icon-search"></i>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <!-- END GALLERY MANAGER PANEL-->
                  <!-- BEGIN GALLERY MANAGER LISTING-->
                  <div class="row-fluid circle-state-overview  no-padding no-margin" style="margin: 0 auto !important;">
                    <% @projects.each do |project| %>
                    <div class="span2 responsive" data-tablet="span3" data-desktop="span2">
        <div class="circle-wrap">
            <div class="stats-circle turquoise-color">
              <%= link_to  project , style: "color:white;text-decoration: none;" do %>
                <i class="icon-pinterest"></i>
                <% end %>
            </div>
            <p>
              <%= link_to  project , style: "color:white;text-decoration: none;" do %>
                <strong><%= project.name %></strong>
                <% end %>
                <%= link_to  project , style: "color:#333;text-decoration: none;" do %>
                <i class="small">Last Updated on <%= Time.now.strftime('%d %B %Y') %></i>
                <% end %>
                <i class="small">
                <% project.users.each do |user| %>
                    <%= user.name %>,
                  <% end %>
                </i>
            </p>
        </div>
    </div>
                    <% end %>
                  </div>
                  <!-- END GALLERY MANAGER LISTING-->
                </div>
              </div>
              <!-- END GALLERY MANAGER PORTLET-->

app/views/projects/new.html.erb
<div class="row-fluid">
 <div class="span12">
    <div class="widget">
      <div class="widget-title">
         <h4><i class="icon-book"></i>New Project</h4>
      </div>
      <div class="widget-body">

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
   <div class="span12">
      <div class="widget">
            <div class="widget-title">
               <h4><i class="icon-pinterest"></i><%= @project.name %></h4>
            </div>
            <div class="widget-body">
                <div class="span3">
                    <div class="text-center profile-pic">
                        <div class="circle-wrap center">
                              <div class="stats-circle turquoise-color">
                                  <i class="icon-pinterest" ></i>
                              </div>
                              <p class="align:center">
                                  <strong><%= @project.name %></strong>
                              </p>
                          </div>
                    </div>
                    <ul class="nav nav-tabs nav-stacked">
                        <li><a href="javascript:void(0)"><i class="icon-group"></i> Members</a></li>
                        <% @project.users.each do |user| %>
                          <li><a href="javascript:void(0)"><i class="icon-user"></i> <%= user.name.camelize %></a></li>
                        <% end %>
                    </ul>
                    <ul class="nav nav-tabs nav-stacked">
                        <li>
                          <%= link_to dashboard_project_path(@project) do %>
                            <i class="icon-bar-chart"></i> Dashboard
                          <% end %>
                        </li>
                        <li><a href="javascript:void(0)"><i class="icon-paper-clip"></i> Tasks</a></li>
                        <li><a href="javascript:void(0)"><i class="icon-comments"></i> Discussions</a></li>
                    </ul>
                    <ul class="nav nav-tabs nav-stacked">
                        <li>
                          <%= link_to  edit_project_path(@project), class: "" do %>
                          <i class="icon-pencil"></i> Update
                          <% end %>
                        </li>
                        <li>
                          <%= link_to project_path(@project), method: :delete, data: { confirm: 'Are you sure delete this project?' } do  %>
                            <i class="icon-trash"></i> Destroy
                          <% end %>
                        </li>
                    </ul>
                </div>
                <div class="span6">
                    <h4>Timeline <br/></h4>
                    <table class="table table-borderless">
                        <tbody>
                        <tr>
                            <td class="span2">Start Date :</td>
                            <td><%= @project.created_at.strftime('%d %B %Y') %></td>
                        </tr>
                        <tr>
                            <td class="span2">End Date :</td>
                            <td>Undefined</td>
                        </tr>
                        <tr>
                            <td class="span2">Time Left :</td>
                            <td><%= distance_of_time_in_words @project.created_at, Time.now %></td>
                        </tr>
                        <tr>
                            <td class="span2">Project Manager :</td>
                            <td><%= @project.users.where("users.role='manager' or users.role='senior_staff'").first.name unless @project.users.where("users.role='manager' or users.role='senior_staff'").nil? %></td>
                        </tr>
                        <tr>
                            <td class="span2">Member :</td>
                            <td><%= @project.users.count %></td>
                        </tr>
                        </tbody>
                    </table>
                    <h4>Description</h4>                    
                    <div class="well">
                        <address>
                            <strong><%= @project.description %></strong><br>
                        </address>
                    </div>
                            <!-- BEGIN CHAT PORTLET-->
                            <div class="widget" id="">
                                <div class="widget-title">
                                    <h4><i class="icon-comments-alt"></i> Discussion</h4>
                                </div>
                                <div class="widget-body">
                                    <ul class="chats normal-chat">
                                      <% @project.discussions.each do |discussion| %>
                                        <li class="in">
                                          <%= image_tag avatar_url(User.find(discussion.user_id)),  :class => "avatar" %>
                                          
                                                <div class="message ">
                                                    <span class="arrow"></span>
                                                    <a href="#" class="name"><%= discussion.user.name.camelize %></a>
                                                    <span class="datetime">at <%= discussion.created_at.strftime('%d %B, %Y %H:%M') %></span>
                                                    <span class="body">
                                                      <%= discussion.content %>
                                                    </span>
                                                    <%= link_to '[edit]', edit_project_discussion_path(discussion.discussrefer_id, discussion.id) %>
                                                      <%= link_to '[x]', project_discussion_path(discussion.discussrefer_id, discussion.id) , method: :delete, data: { confirm: 'Are you sure?' } %>
                                                </div>
                                            </li>
                                      <% end %>
                                        </ul>
                                        <%= simple_form_for([@project, @discussion]) do |f| %>
                                    <div class="chat-form">
                                        <div class="input-cont">
                                          <%= f.input :content, :class => "btn btn-primary", :as => "string", :placeholder => "Type an opinion here...", :label => false %>
                                        </div>
                                        <div class="btn-cont">
                                          <%= f.submit "Send", :class => "btn btn-primary" , :style => "margin-top: 0px"%>
                                        </div>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                            <!-- END CHAT PORTLET-->
                </div>
                <div class="span3">
                    <h4>Project Status</h4>
                    <div class="span10">
                      <span class="label label-inverse clearfix"><%= @todo_persen > 0 ? @todo_persen.round(1) : 0 %> %</span><br/><br/>
                          <div class="progress progress-success progress-striped">
                              <div style="width: <%= @todo_persen > 0 ? @todo_persen.round(1) : 0 %>%" class="bar"></div>
                          </div>
                    </div>
                    <div class="span10">
                    <h4>Task Updated</h4>
                    <%= simple_form_for([@project, @task]) do |f| %>
                      <div class="chat-form">
                          <div class="input-cont">
                            <%= f.input :name, :class =>"span8", :as => "string", :placeholder => "Add Task here..", :label => false %>
                          </div>
                          <div class="btn-cont">
                            <%= f.submit "+", :class => "btn btn-primary", :style => "margin-top: 0px" %>
                          </div>
                      </div>
                      <% end %>
                    <ul class="icons push">
                    <% @project.tasks.last(5).each do |task| %>
                        <li><i class="icon-paper-clip"></i> <strong><%= link_to task.name, project_task_path(task.project, task) %></strong><br/><em><%= task.description.truncate(20) unless task.description.nil?%></em><br>
                          <%= link_to '[edit]', edit_project_task_path(task.project_id, task.id) %> 
                          <%= link_to '[x]', project_task_path(task.project_id, task.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                          <%= link_to "[#{task.todos.count} to do's]", project_task_path(task.project_id, task.id) %>
                        </li>
                        <% end %>
                    </ul>
                    <h4>Similiar Projects</h4>
                    <ul class="">
                      <% current_user.projects.where('projects.id <> ?', @project.id).each do |project| %>
                        <li>
                          <%= link_to project_path(project) do %>
                           <strong><%= project.name %></strong> 
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                <div class="space5"></div>
            </div>
      </div>
   </div>
</div>
<!-- END PAGE CONTENT-->