config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users do
    collection { post :search, to: "users#index"}
    collection { get :search, to: "users#index"}
    get :autocomplete_tag_name, :on => :collection
    member do
      get "profile"
      post "ganti_profile"
    end
  end

  resources :projects do 
    get :dashboard, on: :member
    resources :discussions
    resources :tasks do 
      resources :todos do
        post 'completed'
        resources :discussions
      end
    end
  end

  resources :time_sheets do
    collection do
      delete 'finish' #use delete method to overide link using post data update end time working
      delete 'continue_working' #use delete method to overide link using post to delete the end working time so you can contiue working 
    end
  end
  resources :furloughs
  resources :staff_leaves
  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :name, presence: true
  validate :has_users?

  belongs_to :user, class_name: "User", foreign_key: "completed_by_id"
  belongs_to :task
  belongs_to :project
  has_many :discussions, as: :discussrefer
  has_and_belongs_to_many :users

  def has_users?
    errors.add(:users, 'Please select one user') if self.users.blank?
  end

  def completed_it(uid)
    self.completed_at = Time.new.to_time.strftime('%H:%M:%S').to_time
    self.completed = true
    self.completed_by_id = uid
    self.save!
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_task
  before_action :set_project
  load_and_authorize_resource 

  # GET /todos
  # GET /todos.json
  def index
      @todos = Todo.find_by_task_id(params[:task])
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @discussionrefer = @todo
    @discussions = @discussionrefer.discussions
    @discussion = Discussion.new
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = @task.todos.new(todo_params)

    respond_to do |format|
      if @todo.save
        # format.html { redirect_to project_task_todos_path(@task.project_id, @task), notice: 'Todo was successfully created.' }
        # Notifier.todo_assignation(current_user, @todo).deliver
        NotifiersWorker.perform_async('todo_assignation', current_user.id, nil, @todo.id)
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        # Notifier.todo_assignation(current_user, @todo).deliver
        # raise current_user.to_yaml
        NotifiersWorker.perform_async('todo_assignation', current_user.id, nil, @todo.id)
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      # format.html { redirect_to project_task_todos_path(@todo.task.project.id, @todo.task_id), notice: "Todo #{@todo.name.to_s} was successfully destroyed." }
      format.html { redirect_to project_task_path(@task.project, @task), notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def completed
    @todo = Todo.find(params[:todo_id])
    if @todo.completed_it(current_user.id)
      NotifiersWorker.perform_async('todo_completion', current_user.id, nil, @todo.id)
      redirect_to :back, notice: "Thanks for complete todo"
    else
      flash[:error] = "Fail complete todo"
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end
    def set_task
      @task = Task.find(params[:task_id]) 
    end
    def set_project
      @project = Project.find(params[:project_id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :description, :task_id, :user_ids, :project_id)
    end


    def current_ability
      @current_ability ||= Ability.new(current_user, params)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= simple_form_for([@project, @task, @todo]) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name, label: 'Todo' %>
  </div>
  <div class="field">
    <%= f.association :users, required: true, label: 'Todo for', collection: @project.users, :input_html => {:multiple => false} %>
  </div>
  <div class="field">
    <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id } %>
    <%= f.input :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_form_discussions.html.erb
<%# raise @todo.to_yaml %>
<%= simple_form_for([@project, @task, @todo, @discussion]) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :content%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="row-fluid">
 <div class="span12">
    <div class="widget">
      <div class="widget-title">
         <h4><i class="icon-book"></i>Editing Todo</h4>
      </div>
      <div class="widget-body">

<p>
  <strong>Project Name:</strong>
  <%= link_to @project.name, project_path(@project) %>
</p>
<hr>
<p>
  <strong>Task Name:</strong>
  <%= link_to @task.name, project_task_path(@project, @task) %>
</p>
<hr>

<%= render 'form' %>

<%= link_to 'Show Todo', project_task_todo_path(@project, @task, @todo) %> |
<%= link_to 'Back to Task', project_task_path(@project, @task) %>

      </div>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task.todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td><%= todo.task_id %></td>
        <td><%= link_to 'Show', project_task_todo_path(todo.task.project.id, todo.task_id, todo) %></td>
        <td><%= link_to 'Edit', edit_project_task_todo_path(todo.task.project.id, todo.task_id, todo) %></td>
        <td><%= link_to 'Destroy', project_task_todo_path(todo.task.project.id, todo.task_id, todo), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_project_task_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', project_task_path(@task.project_id, @task.id) %>

app/views/todos/show.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="widget">
      <div class="widget-title">
          <h4><i class="icon-book"></i>Detail Todo</h4>
      </div>
      <div class="widget-body">
        <p>
          <strong>Project Name:</strong>
          <%= link_to @project.name, project_path(@project) %>
        </p>
        <hr>
        <p>
          <strong>Task Name:</strong>
          <%= link_to @task.name, project_task_path(@project, @task) %>
        </p>
        <hr>

        <p>
          <strong>Todo:</strong>
          <%= @todo.name %>
        </p>
        <p>
          <strong>Description:</strong>
          <%= @todo.description %>
        </p>
        <p>Todo for: <%= @todo.users.map(&:name).join(', ') %></p>
        <p>
        <% if @todo.completed %>
        Done by: <%= @todo.user.try(:name) %><br>
        At: <%= @todo.completed_at.strftime('%a, %b %e, %Y %R') %>
        <% else %>
        <%= link_to 'Completed!!', project_task_todo_completed_path(@todo.task.project, @todo.task, @todo), method: :post, data: { confirm: 'Sure completed?' }, class: "btn btn btn-primary" %>
        <% end %>
        </p>

        <%= link_to 'Edit', edit_project_task_todo_path(@todo.task.project.id, @todo.task_id, @todo) %> |
        <%= link_to 'Back to Task', project_task_path(@todo.task.project, @todo.task) %>

      </div>
      <h4>Discussions</h4>
      <ul>
        <% @todo.discussions.each do |discussion| %>
          <li>
            <p>Commmented By <b><%= discussion.user.name %></b></p>
            <p><%= discussion.content %></p>
            <!-- <p><%= link_to 'Edit', edit_project_discussion_path(discussion.discussrefer_id, discussion.id) %> | <%= link_to 'Delete', project_discussion_path(discussion.discussrefer_id, discussion.id), method: :delete, data: { confirm: 'Are you sure?' } %></p> -->
          </li>
        <% end %>
      </ul>
      <%= render 'form_discussions' %>
    </div>
  </div>
</div>