config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users do
    collection { post :search, to: "users#index"}
    collection { get :search, to: "users#index"}
    get :autocomplete_tag_name, :on => :collection
    member do
      get "profile"
      post "ganti_profile"
    end
  end

  resources :projects do 
    get :dashboard, on: :member
    resources :discussions
    resources :tasks do 
      resources :todos do
        post 'completed'
        resources :discussions
      end
    end
  end

  resources :time_sheets do
    collection do
      delete 'finish' #use delete method to overide link using post data update end time working
      delete 'continue_working' #use delete method to overide link using post to delete the end working time so you can contiue working 
    end
  end
  resources :furloughs
  resources :staff_leaves
  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <title>Software Seni Hub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- BEGIN BODY -->
<body class="fixed-top">
  <div id="header" class="navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner">
      <div class="container-fluid">
        <!-- BEGIN LOGO -->
         <%= link_to root_path, class: "brand" do %>
          <img src="/img/logo.png" alt="Software Seni Hub" class="center" />
        <% end %>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="arrow"></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->

                <div class="top-nav ">
                    <ul class="nav pull-right top-menu" >
                      <% if(user_signed_in?) %>
            <!-- BEGIN USER LOGIN DROPDOWN -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="/img/avatar1_small.png" alt="">
                <span class="username"><%= current_user.name %></span>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to profile_user_path(current_user) do  %>
                    <i class="icon-user"></i> My Profile
                  <% end %>
                  
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="icon-user"></i> Logout
                    <% end %>
                </li>
                <% else %>
                <li class="dropdown">
                  <%= link_to user_session_path, class: "dropdown-toggle" do %>
                    <img src="/img/avatar1_small.png" alt="">
                    <span class="username">Login</span>
                    <b class="caret"></b>
                  <% end %>    
                </li>
                <% end %>
              </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->
          </ul>
          <!-- END TOP NAVIGATION MENU -->
        </div>
      </div>
    </div>
    <!-- END TOP NAVIGATION BAR -->
  </div>
  <!-- END HEADER -->
  <!-- BEGIN CONTAINER -->
  <div id="container" class="row-fluid">
    <!-- BEGIN SIDEBAR -->
    <div id="sidebar" class="nav-collapse collapse">
      <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
      <div class="sidebar-toggler hidden-phone"></div>
      <!-- BEGIN SIDEBAR TOGGLER BUTTON -->

      <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
      <div class="navbar-inverse">
        <form class="navbar-search visible-phone">
          <input type="text" class="search-query" placeholder="Search" />
        </form>
      </div>
      <!-- END RESPONSIVE QUICK SEARCH FORM -->
      <% if(user_signed_in?) %>
      <!-- BEGIN SIDEBAR MENU -->
      <ul class="sidebar-menu">
        <li class="">
          <%= link_to dashboard_index_path do  %>
              <span class="icon-box"> <i class="icon-dashboard"></i></span> Dashboard
          <% end %>
        </li>
        <% if can? :create, User %>
        <li class="">
          <%= link_to users_path do  %>
          <span class="icon-box"> <i class="icon-user"></i></span>  User
          <% end %>
        </li>
        <% end %>
        <% if can? :create, TimeSheet %>
        <li class="has-sub active">
          <a href="javascript:;" class="">
          <%= link_to time_sheets_path do  %>
            <span class="icon-box"> <i class="icon-book"></i></span>  TimeSheet
          <% end %>
          <ul class="sub">
            <li>
              <%= link_to 'My Attendance', time_sheets_path %>
            </li>
            <li>
              <%= link_to 'OnLeave List',furloughs_path %>
            </li>
            <%# raise current_user.to_yaml %>

            <% if current_user.role == 'manager' %>
              <li>
                <%= link_to 'Staffs Leave List',staff_leaves_path %>
              </li>
            <% end %>
          </ul>
          <% end %>
        <li class="active has-sub">
          <%= link_to projects_path do  %>
          <span class="icon-box"> <i class="icon-book"></i></span>  Project
          <% end %>
          <% if(current_user.projects) %>
          <ul class="sub">
            <% current_user.projects.each do |project| %>
            <li><%= link_to project.name.camelize, dashboard_project_path(project) %></li>
            <% end %>
          </ul>
          <% end %>
        </li>
      </ul>
      <!-- END SIDEBAR MENU -->
      <% end %>
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div id="main-content">
      <!-- BEGIN PAGE CONTAINER-->
      <div class="container-fluid">
        
        <!-- BEGIN PAGE CONTENT-->
        <div id="page" class="dashboard" >
          <br/>
          <% if(notice) %>
          <p class="notice"><%= notice %></p>
          <% end %>
          <% if(alert) %>
          <p class="alert"><%= alert %></p>
          <% end %>
                    
<%= yield %>
</div>
        <!-- END PAGE CONTENT-->
      </div>
      <!-- END PAGE CONTAINER-->
    </div>
    <!-- END PAGE -->
  </div>
  <!-- END CONTAINER -->
  <!-- BEGIN FOOTER -->
  <div id="footer">
    2014 &copy; Software Seni Hub.
    <div class="span pull-right">
      <span class="go-top"><i class="icon-arrow-up"></i></span>
    </div>
  </div>

  <script>
    jQuery(document).ready(function() {
      // initiate layout and plugins
      App.setMainPage(true);
      App.init();
      
    });
  </script>
  
</body>
<!-- END BODY -->
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <title>Software Seni Hub</title>
  <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'login', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="login-body">
  <div class="login-header">
      <!-- BEGIN LOGO -->
      <div id="logo" class="center">
        
        <%= link_to root_path, class: "center" do %>
          <img src="/img/logo.png" alt="Software Seni Hub" class="center" />
        <% end %>
      </div>
      <!-- END LOGO -->
  </div>
  <%= yield %>
</body>
</html>